#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Please run this script as root !"
  exit
fi
echo -n "Start osmoBTS ? [y/n] : "
read a
if [ "$a" != "${a#[Yy]}" ] ;then
    echo -n "Enabling osmoBTS ... "
    systemctl enable osmo-bsc.service
    systemctl enable osmo-hlr.service
    systemctl enable osmo-msc.service
    systemctl enable osmo-trx-lms.service
    systemctl enable osmo-bts-trx.service
    systemctl enable osmo-mgw.service
    systemctl enable osmo-stp.service
    systemctl enable osmo-pcu.service
    systemctl enable osmo-sgsn.service
    systemctl enable osmo-ggsn.service
    echo "Done."
    echo -n "(re)Starting osmoBTS ... "
    systemctl restart osmo-bsc.service
    systemctl restart osmo-hlr.service
    systemctl restart osmo-msc.service
    systemctl restart osmo-trx-lms.service
    systemctl restart osmo-bts-trx.service
    systemctl restart osmo-mgw.service
    systemctl restart osmo-stp.service
    systemctl restart osmo-pcu.service
    systemctl restart osmo-sgsn.service
    systemctl restart osmo-ggsn.service
    echo "Done."
fi
