#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Please run this script as root !"
  exit
fi
route add -net 192.168.10.0/24 gw 192.168.1.240
ifconfig enp0s3:0 192.168.1.66
echo 1 >/proc/sys/net/ipv4/ip_forward
iptables-restore <iptables.save
